// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpVB_lgOKJR_Poq9qOP80nxHLcZGTj_8',
    appId: '1:275380816831:web:096f0a096f0a096f096f0a',
    messagingSenderId: '275380816831',
    projectId: 'chanzel-c9602',
    authDomain: 'chanzel-c9602.firebaseapp.com',
    storageBucket: 'chanzel-c9602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpVB_lgOKJR_Poq9qOP80nxHLcZGTj_8',
    appId: '1:275380816831:android:f9b9ba216dd08660096f0a',
    messagingSenderId: '275380816831',
    projectId: 'chanzel-c9602',
    storageBucket: 'chanzel-c9602.firebasestorage.app',
  );



  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmpVB_lgOKJR_Poq9qOP80nxHLcZGTj_8',
    appId: '1:275380816831:windows:096f0a096f0a096f096f0a',
    messagingSenderId: '275380816831',
    projectId: 'chanzel-c9602',
    storageBucket: 'chanzel-c9602.firebasestorage.app',
  );
}
