class EgyptianCities {
  static const List<String> cities = [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra El Kheima',
    'Port Said',
    'Suez',
    'Luxor',
    'Mansoura',
    'El-Mahalla El-Kubra',
    'Assiut',
    'Tanta',
    'Fayoum',
    'Zagazig',
    'Ismailia',
    'Aswan',
    'Damietta',
    'Damanhur',
    'El-Minya',
    'Beni Suef',
    'Hurghada',
    'Sharm El Sheikh',
    'El-Arish',
    'Sohag',
    'Qena',
    'Banha',
    'Kafr El-Sheikh',
    'Arish',
    'El-Tor',
    'Ras Gharib',
    'Marsa Alam',
    'El-Quseir',
    'Safaga',
    'El-Gouna',
    'Siwa',
    'Bahariya',
    'Farafra',
    'Dakhla',
    'Kharga',
    'El-Kharga',
    'El-Dakhla',
    'El-Farafra',
    'El-Bahariya',
    'El-Siwa',
    'El-Gouna',
    'El-Safaga',
    'El-Quseir',
    'El-Marsa Alam',
    'El-Ras Gharib',
    'El-Tor',
    'El-Arish',
    'El-Kafr El-Sheikh',
    'El-Banha',
    'El-Qena',
    'El-Sohag',
    'El-Beni Suef',
    'El-Minya',
    'El-Damanhur',
    'El-Damietta',
    'El-Aswan',
    'El-Ismailia',
    'El-Zagazig',
    'El-Fayoum',
    'El-Tanta',
    'El-Assiut',
    'El-Mahalla El-Kubra',
    'El-Mansoura',
    'El-Luxor',
    'El-Suez',
    'El-Port Said',
    'El-Shubra El Kheima',
    'El-Giza',
    'El-Alexandria',
    'El-Cairo',
  ];

  static String getCountry() => 'Egypt';
}
